package com.java.Complaint;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "Complaint")
public class Complaint {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ComplaintID")
	private int complaintID; // Assuming auto-generated by database

	@Column(name = "ComplaintType")
	private String complaintType;

	@Column(name = "CDescription")
	private String cDescription;

	@Column(name = "ComplaintDate")
	private Timestamp complaintDate;

	@Column(name = "Severity")
	private String severity;

	@Column(name = "Status")
	private String status = "Pending";

	/**
	 * @return the complaintID
	 */
	public int getComplaintID() {
		return complaintID;
	}

	/**
	 * @param complaintID the complaintID to set
	 */
	public void setComplaintID(int complaintID) {
		this.complaintID = complaintID;
	}

	/**
	 * @return the complaintType
	 */
	public String getComplaintType() {
		return complaintType;
	}

	/**
	 * @param complaintType the complaintType to set
	 */
	public void setComplaintType(String complaintType) {
		this.complaintType = complaintType;
	}

	/**
	 * @return the cDescription
	 */
	public String getcDescription() {
		return cDescription;
	}

	/**
	 * @param cDescription the cDescription to set
	 */
	public void setcDescription(String cDescription) {
		this.cDescription = cDescription;
	}

	/**
	 * @return the complaintDate
	 */
	public Timestamp getComplaintDate() {
		return complaintDate;
	}

	/**
	 * @param complaintDate the complaintDate to set
	 */
	public void setComplaintDate(Timestamp complaintDate) {
		this.complaintDate = complaintDate;
	}

	/**
	 * @return the severity
	 */
	public String getSeverity() {
		return severity;
	}

	/**
	 * @param severity the severity to set
	 */
	public void setSeverity(String severity) {
		this.severity = severity;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "Complaint [complaintID=" + complaintID + ", complaintType=" + complaintType + ", cDescription="
				+ cDescription + ", complaintDate=" + complaintDate + ", severity=" + severity + ", status=" + status
				+ "]";
	}

	public Complaint() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Complaint(int complaintID, String complaintType, String cDescription, Timestamp complaintDate,
			String severity, String status) {
		super();
		this.complaintID = complaintID;
		this.complaintType = complaintType;
		this.cDescription = cDescription;
		this.complaintDate = complaintDate;
		this.severity = severity;
		this.status = status;
	}

	// Getters and setters

}
